### ISSUE TITLE
打开报异常Could not find class 'android.support.design.internal.NavigationMenuPresenter', 

### ISSUE THREAD

**Issue by fannahlin** [chenyangcun/MaterialDesignExample#3]
02-16 17:18:47.316 19628-19628/com.aswifter.materialexample E/dalvikvm: Could not find class 'android.support.design.internal.NavigationMenuPresenter', referenced from method android.support.design.widget.NavigationView.<init>
02-16 17:18:47.317 19628-19628/com.aswifter.materialexample E/dalvikvm: Could not find class 'android.support.v7.internal.view.SupportMenuInflater', referenced from method android.support.design.widget.NavigationView.getMenuInflater
02-16 17:18:47.350 19628-19628/com.aswifter.materialexample E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              java.lang.RuntimeException: Unable to start activity ComponentInfo{com.aswifter.materialexample/com.aswifter.material.MainActivity}: android.view.InflateException: Binary XML file line #28: Error inflating class android.support.design.widget.NavigationView
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2365)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2417)
                                                                                  at android.app.ActivityThread.access$600(ActivityThread.java:169)
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1383)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                  at android.os.Looper.loop(Looper.java:194)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5409)
                                                                                  at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                  at java.lang.reflect.Method.invoke(Method.java:525)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:897)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:664)
                                                                                  at dalvik.system.NativeStart.main(Native Method)
                                                                               Caused by: android.view.InflateException: Binary XML file line #28: Error inflating class android.support.design.widget.NavigationView
                                                                                  at android.view.LayoutInflater.createView(LayoutInflater.java:613)
                                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
                                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
                                                                                  at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256)
                                                                                  at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
                                                                                  at com.aswifter.material.MainActivity.onCreate(MainActivity.java:31)
                                                                                  at android.app.Activity.performCreate(Activity.java:5141)
                                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1146)
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2329)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2417) 
                                                                                  at android.app.ActivityThread.access$600(ActivityThread.java:169) 
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1383) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:107) 
                                                                                  at android.os.Looper.loop(Looper.java:194) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5409) 
                                                                                  at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                  at java.lang.reflect.Method.invoke(Method.java:525) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:897) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:664) 
                                                                                  at dalvik.system.NativeStart.main(Native Method) 
                                                                               Caused by: java.lang.reflect.InvocationTargetException
                                                                                  at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                                  at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
                                                                                  at android.view.LayoutInflater.createView(LayoutInflater.java:587)
                                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687) 
                                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
                                                                                  at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256) 
                                                                                  at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109) 
                                                                                  at com.aswifter.material.MainActivity.onCreate(MainActivity.java:31) 
                                                                                  at android.app.Activity.performCreate(Activity.java:5141) 
                                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1146) 
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2329) 
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2417) 
                                                                                  at android.app.ActivityThread.access$600(ActivityThread.java:169) 
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1383) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:107) 
                                                                                  at android.os.Looper.loop(Looper.java:194) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5409) 
                                                                                  at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                  at java.lang.reflect.Method.invoke(Method.java:525) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:897) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:664) 
                                                                                  at dalvik.system.NativeStart.main(Native Method) 
                                                                               Caused by: java.lang.NoClassDefFoundError: android.support.design.internal.NavigationMenuPresenter
                                                                                  at android.support.design.widget.NavigationView.<init>(NavigationView.java:80)
                                                                                  at android.support.design.widget.NavigationView.<init>(NavigationView.java:92)
                                                                                  at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                                  at java.lang.reflect.Constructor.newInstance(Constructor.java:417) 
                                                                                  at android.view.LayoutInflater.createView(LayoutInflater.java:587) 
                                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687) 
                                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
                                                                                  at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256) 
                                                                                  at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109) 
                                                                                  at com.aswifter.material.MainActivity.onCreate(MainActivity.java:31) 
                                                                                  at android.app.Activity.performCreate(Activity.java:5141) 
                                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1146) 
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2329) 
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2417) 
                                                                                  at android.app.ActivityThread.access$600(ActivityThread.java:169) 
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1383) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:107) 
                                                                                  at android.os.Looper.loop(Looper.java:194) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5409) 
                                                                                  at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                  at java.lang.reflect.Method.invoke(Method.java:525) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:897) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:664) 
                                                                                  at dalvik.system.NativeStart.main(Native Method)

**Comment by jp1017** [comment]
你好，我也遇到了这个问题，请问你解决了吗?

**Comment by chenyangcun** [comment]
请问你用的是什么版本的Android Studio？

**Comment by chenyangcun** [comment]
79fedf98ba81ee3c17d0ff1b3f2e9532f65cd959

**Comment by fannahlin** [comment]
抱歉没有看到。 
用的android studio1.5




------------------ 原始邮件 ------------------
发件人: "阳春面";<notifications@github.com>;
发送时间: 2016年3月27日(星期天) 上午8:53
收件人: "chenyangcun/MaterialDesignExample"<MaterialDesignExample@noreply.github.com>; 
抄送: "小精灵"<181327140@qq.com>; 
主题: Re: [MaterialDesignExample] 打开报异常Could not find class 'android.support.design.internal.NavigationMenuPresenter',  (#3)




请问你用的是什么版本的Android Studio？
